[Indice](index.ipynb) | Previo: [RelatividadGeneral.InerciaYGeodesicas](01.05.00.00.RelatividadGeneral.InerciaYGeodesicas.ipynb) | 


## Transporte paralelo y curvatura {#tparalelo_curvatura}

En una sección anterior vimos dos situaciones diferentes en el transporte paralelo: en espacio plano y en espacio curvo (ver figuras abajo) y un hecho es notable: al recorrer una trayectoria cerrada en el espacio plano un vector transportado de forma paralela no se modifica.  Sin embargo en otro tipo de espacio (sobre la superficie de una esfera), sobre una trayectoria circular un vector transportado de forma paralela no vuelve a ser lo mismo. 

<a id='fig:Figure_11'></a>![Figura](./figures/square-tparalelo-plano.png)

<center><b>Figura 1.11</b>. Figura</center>
<a id='fig:Figure_11'></a>![Figura](./figures/square-tparalelo-esferico.png)

<center><b>Figura 1.11</b>. Figura</center>

¿Por qué ocurre esto? ¿de qué depende?

Otra manera de expresar la diferencia es decir que el vector transportado de forma paralela depene del camino que se siga.  En la figura se muestra el transporte paralelo de un vector $A^\mu$ desde un punto $P$ hasta un punto $Q$ por dos caminos diferentes $\mathrm{d}x^\alpha\rightarrow \mathrm{d}x^\beta$ y $\mathrm{d}x^\beta\rightarrow \mathrm{d}x^\alpha$

<a id='fig:Figure_12'></a>![Figura](./figures/square-diferencia-curvatura.png)

<center><b>Figura 1.12</b>. Figura</center>

La diferencia a través de los dos recorridos la hemos llamado $\mathrm{d}^2A^\mu$.

Usemos la derivada covariante para el transporte paralelo hasta los puntos intermedios $R$ y $S$:

$$
A^\mu_{\parallel,\mathrm{R}}=A^\mu+\mathrm{D}_\beta A^\mu \mathrm{d}x^\beta
$$

Ror otro lado es transporte de $S$ a $Q$ es:

$$
A^\mu_{\parallel,\mathrm{RQ}}=A^\mu_{\parallel,\mathrm{R}}+\mathrm{D}_\alpha A^\mu_{\parallel,\mathrm{R}} \mathrm{d}x^\alpha
$$
reemplazando lo obtenido antes obtenemos:

$$
A^\mu_{\parallel,\mathrm{RQ}}=A^\mu+\mathrm{D}_\beta A^\mu \mathrm{d}x^\beta+\mathrm{D}_\alpha A^\mu \mathrm{d}x^\alpha+\mathrm{D}_{\alpha\beta} A^\mu \mathrm{d}x^\alpha\mathrm{d}x^\beta
$$

El recorrido por el otro recorrido es:

$$
A^\mu_{\parallel,\mathrm{SQ}}=A^\mu+\mathrm{D}_\alpha A^\mu \mathrm{d}x^\alpha+\mathrm{D}_\beta A^\mu \mathrm{d}x^\beta+\mathrm{D}_{\beta\alpha} A^\mu \mathrm{d}x^\alpha\mathrm{d}x^\beta
$$

Tomando la diferencia obtenemos:

$$
\mathrm{d}^2 A^\mu=A^\mu_{\parallel,\mathrm{SQ}}-A^\mu_{\parallel,\mathrm{RQ}}=-(\mathrm{D}_{\alpha\beta}-\mathrm{D}_{\beta\alpha}) A^\mu \mathrm{d}x^\alpha\mathrm{d}x^\beta
$$

Por otro lado podemos suponer que la diferencia entre el vector transportado por los dos caminos se puede expresar como:

$$
\mathrm{d}^2 A^\mu\equiv R^\mu_{\delta\alpha\beta}A^\delta \mathrm{d}x^\alpha\mathrm{d}x^\beta
$$
donde los nuevos coeficientes $R^\mu_{\delta\alpha\beta}$ juegan el papel que en el transporte paralelo convencional jugaban los coeficientes de conexión.

Comparando encontramos que la manera de cálcular los coeficientes es:

$$
R^\mu_{\delta\alpha\beta}A^\delta=-(\mathrm{D}_{\alpha\beta}-\mathrm{D}_{\beta\alpha}) A^\mu 
$$

O en la notación punto y coma de la derivada covariante:

$$
R^\mu_{\delta\alpha\beta}A^\delta=-(A^\mu_{;\alpha;\beta}- A^\mu_{;\beta;\alpha}) 
$$

Veamos cómo es la segunda derivada covariante:

$$
\begin{array}{rcl}
{A^\rho}_{;\mu;\nu} & = & ({A^\rho}_{;\nu,\mu})
+[\Gamma_{\mu\sigma}^\rho {A^\sigma}_{;\nu}]
-\{\Gamma_{\mu\nu}^\lambda {A^\rho}_{;\lambda}\}\\
&=&({A^\rho}_{,\nu,\mu}+\Gamma^\rho_{\nu\sigma,\mu}A^\sigma+\Gamma^\rho_{\nu\sigma}{A^\sigma}_{,\mu})+\\
& & +[\Gamma_{\mu\sigma}^\rho {A^\sigma}_{,\nu}+\Gamma_{\mu\sigma}^\rho \Gamma_{\nu\lambda}^\sigma A^\lambda]+\\
& & -\{\Gamma_{\mu\nu}^\lambda {A^\rho}_{,\lambda}+\Gamma_{\mu\nu}^\lambda \Gamma_{\lambda\sigma}^\rho A^\sigma\}
\end{array}
$$

La derivada contraria ${A^\rho}_{;\nu;\mu}$ se obtiene intercambiando en la expresión anterior $\mu\leftrightarrow\nu$.  Es claro que los términos proporcionales a $\Gamma_{\mu\nu}^\lambda$ serán idénticos en ambas derivadas y se eliminaran.  Lo mismo pasa con los términos ${A^\rho}_{,\nu,\mu}$ y $\Gamma^\rho_{\nu\sigma}{A^\sigma}_{,\mu}$ y $\Gamma_{\mu\sigma}^\rho {A^\sigma}_{,\nu}$ que serán idénticos a los correspondientes en la derivada con los índices cambiados.

De modo que nos queda:

$$
A^\sigma_{;\mu;\nu}- A^\sigma_{;\nu;\mu}=(\{\Gamma^\rho_{\nu\sigma,\mu} + \Gamma_{\mu\delta}^\rho \Gamma_{\nu\sigma}^\delta\}-\{\mu\leftrightarrow\nu\})A^\sigma
$$
donde la notación $\{\mu\leftrightarrow\nu\}$ indica que lo que hay antes entre llaves se pone igual pero intercambiando los índices $\mu$ por $\nu$ y viceversa.

Volviendo a la definición de los coeficientes $R$ obtenemos entonces que ellos están dados como función de los símbolos de Christoffel y de sus derivadas en la forma más conveniente:

$$
{R^\rho}_{\sigma\mu\nu}=\{\Gamma^\rho_{\sigma\mu,\nu} + \Gamma_{\sigma\mu}^\delta \Gamma_{\nu\delta}^\rho \}-\{\mu\leftrightarrow\nu\}
$$

Esta cantidad transforma como un tensor (ver Problemas al final del capítulo) y se conoce como el **tensor de Riemann**.

> **Nota: El tensor de Riemann y la curvatura.**<a id=''></a> De acuerdo a lo que habíamos dicho antes, el tensor de Riemann establece si un espacio es curvo o no.  Esta condición puede expresarse de dos maneras:

> - Si **al menos una** de las componentes del tensor de Riemann es distinta de cero, **el espacio es curvo**.
> - Si **todas** las componentes del tensor de Riemann son cero, **el espacio es plano**.

### 1.8.6. Propiedades del tensor de Riemann
<a id='propiedades_riemann'></a>

El tensor de Riemann juega un papel fundamental en la relatividad general de modo que sus propiedades son cruciales para las matemáticas del área.

La primera propiedad y la más obvia es su antisimetría:

$$
{R^\rho}_{\sigma\mu\nu}=-{R^\rho}_{\sigma\nu\mu}\\
{R^\rho}_{\sigma\mu\nu}+{R^\rho}_{\sigma\nu\mu}=0
$$
que podemos escribir también como:

$$
{R^\rho}_{\sigma[\mu\nu]}=0
$$

¿Cuántas componentes tiene el tensor de Riemann?

De la misma manera que los símbolos de Christoffel pueden ser pensados como una "pila de matrices", el tensor de Riemann es como una matriz de matrices:

$$
{R^\rho}_{\sigma\mu\nu}=({R^\rho}_\sigma)_{\mu\nu}
$$
de donde sabemos que en total el número de componentes totales será $N^4$ y para el espacio-tiempo 256 componentes.

Ahora bien, por la antisimetría de $\mu\nu$ sabemos que la diagonal:

$$({R^\rho}_\sigma)_{\mu\mu}=0$$
y por lo tanto cada matriz de matrices tiene por lo menos $N(N-1)/2$ componentes independientes, para un total de $N^3(N-1)/2$ que en el caso de $N=4$ corresponde a 96 componentes independientes.

El número de términos encontrados es todavía muy grande, pero puede mostrarse que es menos si se baja el índice superior:

$$
R_{\lambda\mu\nu\kappa}=g_{\lambda\rho}{R^{\rho}}_{\mu\nu\kappa}
$$

Desarrollando en detalle se puede mostrar (ver Problemas al final del capítulo) que esta versión totalmente covariante del tensor de Riemann es:

$$
\begin{array}{rcl}
R_{\lambda\mu\nu\kappa} & = & -\frac{1}{2}(g_{\mu\nu,\lambda,\kappa}-g_{\nu\lambda,\kappa,\mu}+g_{\lambda\kappa,\mu,\nu}-g_{\kappa\mu,\nu,\lambda})+\\
& & +g_{\sigma\xi}(\Gamma^\sigma_{\mu\kappa}\Gamma^\xi_{\lambda\nu}-\Gamma^\sigma_{\mu\nu}\Gamma^\xi_{\lambda\kappa})
\end{array}
$$

O en notación más compacta:

$$
R_{\lambda\mu\nu\kappa} = -\frac{1}{2} g_{\{\mu\nu,\lambda,\kappa\}}-g_{\alpha\beta}(\Gamma^\alpha_{\mu\nu}\Gamma^\beta_{\lambda\kappa}-\Gamma^\alpha_{\mu\kappa}\Gamma^\beta_{\lambda\nu})
$$

Es decir el tensor de Riemann es proporcional a las **segundas derivadas de la métrica**.

Con esta expresión se identifica dos propiedades:

1. Antisimetría frente al intercambio de los primeros indices:
    $$
    R_{\alpha\beta\mu\nu}=-R_{\beta\alpha\mu\nu}
    $$
    
2. Simetría frente al intercambio de los pares de índices inicial y final:

    $$
    R_{\alpha\beta\mu\nu}=R_{\mu\nu\beta\alpha}
    $$

De modo que tenemos una matriz antisimétrica de matrices antisimétricas.  Eso implica que hay $M=N(N-1)/2$ matrices antisimétricas de $M=N(N-1)/2$ términos, es decir $N^2(N-1)^2/4$, para $N=4$ el número de términos es $4^2(4-1)^2/4=36$ términos independientes.  Esos términos son:

$$
\begin{array}{cccccc}
R_{0101}&R_{0102}&R_{0103}&R_{0112}&R_{0113}&R_{0123}\\
R_{0201}&R_{0202}&R_{0203}&R_{0212}&R_{0213}&R_{0223}\\
R_{0301}&R_{0302}&R_{0303}&R_{0312}&R_{0313}&R_{0323}\\
R_{1201}&R_{1202}&R_{1203}&R_{1212}&R_{1213}&R_{1223}\\
R_{1301}&R_{1302}&R_{1303}&R_{1312}&R_{1313}&R_{1323}\\
R_{2301}&R_{2302}&R_{2303}&R_{2312}&R_{2313}& R_{2323}\\
\end{array}
$$

Pero por la propiedad 2 de más arriba, este arreglo cuadrado de términos es simétrico y por lo tanto de todos estos términos hay $6(6+1)/2=21$ términos independientes.

La conclusión hasta ahora es que para que las componentes del tensor de Riemann que sean independientes y potencialmente distintas de 0 **los primeros indíces y los últimos deben ser diferentes entre sí**.  Las componentes $R_{\alpha\alpha\mu\nu}$ o $R_{\alpha\beta\mu\mu}$ son siempre iguales a cero.

> **Proposición: Identidades de Bianchi.**<a id=''></a> Hay dos propiedades adicionales del tensor de Riemann que pueden llegar a ser de alguna utilidad:

> 1. **Primera identidad de Bianchi**: $R_{\alpha[\beta\mu\nu]}=0$
> 2. **Segunda identidad de Bianchi**: $R^{\alpha}_{\beta[\mu\nu;\sigma]}=0$

### 1.8.7. Desviación geodésica
<a id='desviacion_geodesica'></a>

Aparte de servir para darnos una idea de si un espacio es curvo o plano ¿qué otra función física tiene el tensor de Riemann per se? 

El tensor de Riemann esta relacionado con la **marea gravitacional**.  El fenómeno de marea gravitacional se produce cuando en un sistema de referencia en caída libre (que se mueve sobre una geodésica) 

### 1.8.8. Tensor de Riemann para métricas diagonales
<a id='riemann_diagonal'></a>

Pensemos ahora nuevamente en el caso en el que la métrica es simétrica.  En este caso el tensor de Riemann se simplifica de un general:

$$
R_{\lambda\mu\nu\kappa} = -\frac{1}{2} g_{\{\mu\nu,\lambda,\kappa\}}-g_{\alpha\beta}(\Gamma^\alpha_{\mu\nu}\Gamma^\beta_{\lambda\kappa}-\Gamma^\alpha_{\mu\kappa}\Gamma^\beta_{\lambda\nu})
$$
a uno más particular:

$$
R_{\lambda\mu\nu\kappa} = -\frac{1}{2} g_{\{\mu\nu,\lambda,\kappa\}}-g_{\alpha\alpha}(\Gamma^\alpha_{\mu\nu}\Gamma^\alpha_{\lambda\kappa}-\Gamma^\alpha_{\mu\kappa}\Gamma^\alpha_{\lambda\nu})
$$

De estos aquellos con $\mu=\nu$ y $\lambda\neq \kappa\neq \mu$ serán:

$$
R_{\lambda\mu\mu\kappa} = -\frac{1}{2} g_{\mu\mu,\lambda,\kappa}-g_{\lambda\lambda}\Gamma^\lambda_{\mu\mu}\Gamma^\lambda_{\lambda\kappa}-g_{\kappa\kappa}\Gamma^\kappa_{\mu\mu}\Gamma^\kappa_{\lambda\kappa}+g_{\mu\mu}\Gamma^\mu_{\mu\kappa}\Gamma^\mu_{\lambda\mu}
$$

Y aquellos con $\mu=\nu$ y $\lambda=\kappa$ serán:

$$
R_{\lambda\mu\mu\lambda} = -\frac{1}{2} (g_{\mu\mu,\lambda,\lambda}+g_{\lambda\lambda,\mu,\mu})-g_{\alpha\alpha}\Gamma^\alpha_{\mu\mu}\Gamma^\alpha_{\lambda\lambda}+g_{\lambda\lambda}(\Gamma^\lambda_{\mu\lambda})^2+g_{\mu\mu}(\Gamma^\mu_{\mu\lambda})^2
$$

Y si todos son diferentes $\mu\neq\nu\neq\lambda\neq\kappa$ entonces $R_{\lambda\mu\nu\kappa}=0$.

Esta condición nos deja un potencial de $21-6=15$ componentes del tensor.

### 1.8.9. Tensor de Riemann numérico
<a id='riemann_numerico'></a>

Con las reglas simplificadas de más arriba podemos diseñar una rutina para calcular el tensor de Riemann numérico.

In [1]:
def GammaRiemann(xmu,gfun,gargs,N=4,dxmax=1e-6,verbose=1):
    from scipy.misc import derivative
    from numpy import zeros,where,arange
    R=zeros((N,N,N,N))
    #Indices
    index=arange(N)
    
    #Calcula gamma
    from export import Gamma
    G=Gamma(xmu,gfun,gargs,N)
    if verbose:print(f"G = \n{G}")
    for mu in range(N):
        if verbose:print(f"mu = {mu}")
        for pi in range(N):
            if pi==mu:continue
            if verbose:print(f"\tpi = {pi}")
            for xi in range(N):
                if xi==mu:continue
                if verbose:print(f"\t\txi = {xi}")
                #pi = xi
                if pi==xi:
                    if verbose:print(f"\t\t\tpi = xi")
                    #g_mumu,pi,pi
                    xd=xmu[pi] #Punto de derivación
                    dx=max(dxmax,dxmax*abs(xd))
                    gmumu=lambda x:gfun(where(index==pi,x,xmu),
                                        mu,*gargs)
                    gmumu_pi_pi=derivative(gmumu,xd,dx,n=2)
                    if verbose:print(f"\t\t\tg_{mu}{mu},{pi},{pi} = {gmumu_pi_pi}")
                    #g_pipi,mu,mu
                    xd=xmu[mu] #Punto de derivación
                    dx=max(dxmax,dxmax*abs(xd))
                    gpipi=lambda x:gfun(where(index==mu,x,xmu),
                                        pi,*gargs)
                    gpipi_mu_mu=derivative(gpipi,xd,dx,n=2)
                    if verbose:print(f"\t\t\tg_{pi}{pi},{mu},{mu} = {gpipi_mu_mu}")
                    #Terminos
                    termino1=-0.5*(gmumu_pi_pi+gpipi_mu_mu)
                    termino2=0
                    for a in arange(N):
                        if verbose:print(f"\t\t\t\tg_{a}{a} = {gfun(xmu,a,*gargs)}")
                        if verbose:print(f"\t\t\t\tG^{a}_{mu}{mu} = {G[a,mu,mu]}")
                        if verbose:print(f"\t\t\t\tG^{a}_{pi}{pi} = {G[a,pi,pi]}")
                        termino2-=gfun(xmu,a,*gargs)*G[a,mu,mu]*G[a,pi,pi]
                    termino3=gfun(xmu,pi,*gargs)**2*G[pi,pi,mu]**2
                    termino4=gfun(xmu,mu,*gargs)**2*G[mu,mu,pi]**2
                    if verbose:print(f"\t\t\tTermino 1 = {termino1}")
                    if verbose:print(f"\t\t\tTermino 2 = {termino2}")
                    if verbose:print(f"\t\t\tTermino 3 = {termino3}")
                    if verbose:print(f"\t\t\tTermino 4 = {termino4}")
                    R[pi,mu,mu,xi]=termino1+termino2+termino3+termino4
                    if verbose:print(f"\t\t\tR_{pi}{mu}{mu}{xi} = {R[pi,mu,mu,xi]}")
                #pi != xi
                else:
                    #g_mumu,pi
                    if verbose:print(f"\t\t\tpi != xi")
                    def dgdxpi(xmu_local):
                        x1d=xmu_local[pi] #Punto de derivación
                        dx1=max(dxmax,dxmax*abs(x1d))
                        g=lambda x:gfun(where(index==pi,x,xmu_local),
                                            mu,*gargs)
                        g_pi=derivative(g,x1d,dx1,n=1)
                        return g_pi
                    #g_mumu,pi,xi
                    x2d=xmu[xi] #Punto de derivación
                    dx2=max(dxmax,dxmax*abs(x2d))
                    gmumu_pi=lambda x:dgdxpi(where(index==xi,x,xmu))
                    gmumu_pi_xi=derivative(gmumu_pi,x2d,dx2,n=1)
                    if verbose:print(f"\t\t\tg_{mu}{mu},{pi},{xi} = {gmumu_pi_xi}")
                    #Terminos
                    termino1=-0.5*gmumu_pi_xi
                    termino2=-gfun(xmu,pi,*gargs)*G[pi,mu,mu]*G[pi,pi,xi]
                    termino3=-gfun(xmu,xi,*gargs)*G[xi,mu,mu]*G[xi,xi,pi]
                    termino4=-gfun(xmu,mu,*gargs)*G[mu,mu,pi]*G[mu,mu,xi]
                    R[pi,mu,mu,xi]=termino1+termino2+termino3+termino4
                #print(f"Filling: {pi},{mu},{mu},{xi}")
                R[mu,pi,mu,xi]=-R[pi,mu,mu,xi]
                R[mu,pi,xi,mu]=-R[pi,mu,mu,xi]
                R[mu,xi,mu,pi]=+R[pi,mu,mu,xi]
                R[xi,mu,pi,mu]=-R[pi,mu,mu,xi]
                R[mu,xi,pi,mu]=-R[pi,mu,mu,xi]
                R[xi,mu,mu,pi]=+R[pi,mu,mu,xi]
    return G,R

Probemósla con la esfera:

In [3]:
from export import g_esfera_2d
from numpy import pi
xmu=[pi/6,0]
R=1
N=2
Gama,Riemann=GammaRiemann(xmu,g_esfera_2d,(R,),N)

G = 
[[[-0.          0.        ]
  [ 0.          0.4330127 ]]

 [[-0.         -0.57735027]
  [-0.57735027 -0.        ]]]
mu = 0
	pi = 1
		xi = 1
			pi = xi
			g_00,1,1 = 0.0
			g_11,0,0 = -1.000088900582341
				g_00 = 1
				G^0_00 = -0.0
				G^0_11 = 0.4330127019169794
				g_11 = 0.7500000000000001
				G^1_00 = -0.0
				G^1_11 = -0.0
			Termino 1 = 0.5000444502911705
			Termino 2 = 0.0
			Termino 3 = 0.18750000002144285
			Termino 4 = 0.0
			R_1001 = 0.6875444503126134
mu = 1
	pi = 0
		xi = 0
			pi = xi
			g_11,0,0 = -1.000088900582341
			g_00,1,1 = 0.0
				g_00 = 1
				G^0_11 = 0.4330127019169794
				G^0_00 = -0.0
				g_11 = 0.7500000000000001
				G^1_11 = -0.0
				G^1_00 = -0.0
			Termino 1 = 0.5000444502911705
			Termino 2 = 0.0
			Termino 3 = 0.0
			Termino 4 = 0.18750000002144285
			R_0110 = 0.6875444503126134


In [4]:
Riemann

array([[[[ 0.        ,  0.        ],
         [ 0.        ,  0.        ]],

        [[ 0.        , -0.68754445],
         [ 0.68754445,  0.        ]]],


       [[[ 0.        , -0.68754445],
         [ 0.68754445,  0.        ]],

        [[ 0.        ,  0.        ],
         [ 0.        ,  0.        ]]]])

In [5]:
from export import g_cilindricas_4d
xmu=[0,1,0,0]
N=4
Gama,Riemann=GammaRiemann(xmu,g_cilindricas_4d,(),N)

G = 
[[[-0.  0.  0.  0.]
  [ 0. -0.  0.  0.]
  [ 0.  0. -0.  0.]
  [ 0.  0.  0. -0.]]

 [[ 0. -0.  0.  0.]
  [-0.  0. -0. -0.]
  [ 0. -0. -1.  0.]
  [ 0. -0.  0.  0.]]

 [[ 0.  0. -0.  0.]
  [ 0.  0.  1.  0.]
  [-0.  1.  0. -0.]
  [ 0.  0. -0.  0.]]

 [[ 0.  0.  0. -0.]
  [ 0.  0.  0. -0.]
  [ 0.  0.  0. -0.]
  [-0. -0. -0.  0.]]]
mu = 0
	pi = 1
		xi = 1
			pi = xi
			g_00,1,1 = 0.0
			g_11,0,0 = 0.0
				g_00 = 1
				G^0_00 = -0.0
				G^0_11 = -0.0
				g_11 = -1
				G^1_00 = 0.0
				G^1_11 = 0.0
				g_22 = -1
				G^2_00 = 0.0
				G^2_11 = 0.0
				g_33 = -1
				G^3_00 = 0.0
				G^3_11 = 0.0
			Termino 1 = -0.0
			Termino 2 = 0.0
			Termino 3 = 0.0
			Termino 4 = 0.0
			R_1001 = 0.0
		xi = 2
			pi != xi
			g_00,1,2 = 0.0
		xi = 3
			pi != xi
			g_00,1,3 = 0.0
	pi = 2
		xi = 1
			pi != xi
			g_00,2,1 = 0.0
		xi = 2
			pi = xi
			g_00,2,2 = 0.0
			g_22,0,0 = 0.0
				g_00 = 1
				G^0_00 = -0.0
				G^0_22 = -0.0
				g_11 = -1
				G^1_00 = 0.0
				G^1_22 = -1.000000000001
				g_22 = -1
				G^